### ISSUE TITLE
Failed to invoke @OnEnabled method due to java.lang.ArrayIndexOutOfBoundsException: 0: {}

### ISSUE THREAD

**Issue by huwdjones** [hashmapinc/nifi-opcua-bundle#61]
Hi there,

I followed the set up in the README however the StandardOPCUAService Service Controller seems to be stuck in a constant state of Enabling.

```
2018-09-28 15:19:03,020 ERROR [Timer-Driven Process Thread-5] o.a.n.c.s.StandardControllerServiceNode StandardOPCUAService[id=20a35742-0166-1000-7d4a-d276e0e14317] Failed to invoke @OnEnabled method due to java.lang.ArrayIndexOutOfBoundsException: 0: {}
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.hashmapinc.tempus.processors.StandardOPCUAService.onEnabled(StandardOPCUAService.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:142)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:130)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:75)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:52)
	at org.apache.nifi.controller.service.StandardControllerServiceNode$2.run(StandardControllerServiceNode.java:433)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I don't know whether or not this is related but the GetOPCNodeList property "Starting Nodes" mentioned in the documentation appears to have been replaced with the property "Node Filter". I placed the same string I would have used in the "Starting Nodes" field in the "Node Filter" property. I'm not sure whether or not this is correct - the documentation does not mention this field.

I've also tried various combinations of versions of OPC Foundation project and this bundle but had issues with dependencies.

Any ideas?

Many thanks.

**Comment by cherrera2001** [comment]
Hi @huwdjones I am going to have a look at this now....

**Comment by huwdjones** [comment]
Hi @cherrera2001 thank you. Please let me know if there is anything further I can provide or help in testing.

**Comment by Chouvic** [comment]
Hey everyone, just to mention that I also tried this set up and hit upon the same problem yesterday. Any ideas what the issue is and if there is a fix for it? Thanks.

**Comment by randypitcherii** [comment]
Hey, team. I'm trying to reproduce the issue locally and I'm having trouble even building.

Are you able to build the UA-Java dependency locally? https://github.com/OPCFoundation/UA-Java

I'm getting local errors on multiple versions of Java 6 and Java 8 (using both openJDK and oracle) when building on the `549bb94` commit.

If you're able to build, can you please confirm what commit you're working from on the UA-Java repo and which version of java you're using?

**Comment by randypitcherii** [comment]
```bash
[ERROR] /projects/UA-Java/src/main/java/org/opcfoundation/ua/utils/SunJceUtils.java:[39,16] cannot find symbol
[ERROR]   symbol:   class BASE64Decoder
[ERROR]   location: package sun.misc
```

I'm getting many errors similar to the one above. Maybe there's something I can add to the `pom.xml` to address this?

This may be related to the issues you're having.

**Comment by huwdjones** [comment]
Hi @randypitcherii I managed to build from the `549bb94` commit. I started with Ubuntu 16.04.5 LTS and installed the default mvn package from aptitude. Inspecting the java version shows:

```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

The only changes I had to account for were to have enough memory for compilation and also the `549bb94` commit for UA-Java now builds `opc-ua-stack-1.3.343.jar` rather than the SNAPSHOT jar suggested by the README instructions.

**Comment by vantaka2** [comment]
@huwdjones ; I'm not a Java developer, might be a simple question. 

How did you account for the fact that its building the opc-ua-stack-1.3.343.jar instead of the snapshot jar? 

I was following the readme instructions the 'Execute a maven clean install';

I'm getting the following errors, and it seems like its because it built opc-ua-stack-1.3.343.jar instead of the SNAPSHOT jar. 

'Could not resolve dependencies for project com.hashmapinc.tempus.processors:nifi-opcua-bundle:pom:0.0.1-SNAPSHOT: Failure to find org.opcfoundation.ua:opc-ua-stack:jar:1.3.343 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-sonatype has elapsed or updates are forced"

**Comment by huwdjones** [comment]
@vantaka2 I don't remember exactly now but I think I tried everything from checking out an older version to get the SNAPSHOT, to updating the pom file and editting the name to simply renaming the file to SNAPSHOT. No of these are ideal but it points to potentially further incompatibilities which perhaps is why I cannot get this processor to work...

**Comment by MLIIOTBuild** [comment]
c.h.t.processors.StandardOPCUAService StandardOPCUAService[id=4c60a102-0168-1000-1089-cb0ca8640416] No security mode specified
2019-01-15 15:02:53,630 ERROR [Timer-Driven Process Thread-1] o.a.n.c.s.StandardControllerServiceNode StandardOPCUAService[id=4c60a102-0168-1000-1089-cb0ca8640416] Failed to invoke @OnEnabled method due to java.lang.ArrayIndexOutOfBoundsException: 0: {}
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.hashmapinc.tempus.processors.StandardOPCUAService.onEnabled(StandardOPCUAService.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:142)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:130)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:75)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:52)
	at org.apache.nifi.controller.service.StandardControllerServiceNode$2.run(StandardControllerServiceNode.java:433)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


@cherrera2001  I am also facing same issue any solution for this 
I was trying to connect the remote server, but it works fine if I have OPC server and NiFi in same machine.

**Comment by huwdjones** [comment]
@MLIIOTBuild interestingly I too was trying to connect NiFi to a remote OPC server.

**Comment by Karthikeyyan** [comment]
@cherrera2001 - I am facing the very same issue. Any updates on this post?
* Checked out 549bb94 and built opc-ua-stack-1.3.343.jar
* Successfully able to Maven Build and fetch nifi-opcua-bundle-nar-0.0.1-SNAPSHOT.nar file
* But When I tried to enable StandardOPCUAService Service Controller on NiFi, I get 
Failed to invoke @onEnabled method due to java.lang.ArrayIndexOutOfBoundsException: 0: 0

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
with 
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: C:\Program Files\Apache Software Foundation\apache-maven-3.6.0\bin\..
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_191\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

![Screenshot (25)](https://user-images.githubusercontent.com/43351361/55182601-6683bd80-5164-11e9-92bb-19aa7e5d138c.png) 
I have not tried server and NiFi on same machine, I will try that give my feedback. Thanks!

**Comment by paskl91** [comment]
Hi, We also encountered the same issue, does anyone have a solution for this?
Thx

**Comment by nlesueur31** [comment]
Hi,
I met the same issue with an OPC-UA server simulator (let's call it A) when there is no issue with another one (let's call it B), both on the same machine as NiFi.
After some code analysis here is my understanding: 
* when the StandardOPCUAService Service Controller is enabled it connects a first time to the OPC UA server thanks to the "Endpoint URL" property to collect the list of endpoints available at the OPC UA server (None, Username, Sign, etc.).
* Once collected, the "Endpoint URL" is compared one by one to this list and only endpoints which match are added into an array.
* If none of them matches then the array is empty and its treatment raises the exception ArrayIndexOutOfBoundsException and the service controller is frozen in "Enabling" state.

It appears that:
* The OPC UA server simulator B (with which NiFi works fine) provides an endpoint URL built with my laptop hostname and it provides endpoints list built with the same hostname
* The OPC UA server simulator A (with which NiFi fails) provides an endpoint URL built with my laptop hostname BUT it provides endpoints list built with "localhost". If "localhost" is used in the "Endpoint URL" instead of my laptop hostname then the controller service is enabled sucessfully

I hope this helps.

**Comment by cs111** [comment]
i am facing same issue.
@cherrera2001  please help.
![image](https://user-images.githubusercontent.com/3855874/126772319-ab99cd0e-70e0-4b8c-88d5-c0e35f41bccf.png)

![image](https://user-images.githubusercontent.com/3855874/126772346-a498ee19-55c7-4a63-88de-9806c307553b.png)
![image](https://user-images.githubusercontent.com/3855874/126772611-19bb5e63-581c-4a4c-a02d-3b2982ec78e8.png)

waiting for your ,, please solve this issue

**Comment by sounavo** [comment]
Anyone has solved this issue? Encountering the same 
Failed to invoke @OnEnabled method due to java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0: Index 0 out of bounds for length 0

**Comment by carlosfrutos** [comment]
I also had this problem, and I found the reason.

I'll try to create a PR with the solution. The problem is that the URL from the OPC server MUST match exactly with the property "endpoint URL". Otherwise, it won't match and return 0 elements, hence the ArrayIndexOutOfBounds. In my case, the server was adding a "/OCT" suffix.

The solution I made tries to match the URL with "startsWith" rather than a exact match.
